# Generated by Django 4.2.4 on 2023-09-28 12:04

from django.db import migrations, models
import mainapp.generator


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.PositiveIntegerField(blank=True, default=mainapp.generator.generate_random_number, max_length=6, null=True, unique=True),
        ),
    ]
