# Generated by Django 4.2.4 on 2023-09-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_product_color_product_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='kupon',
            new_name='coupon',
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('Activate', 'Activate'), ('Deactivate', 'Deactivate')], default='Activate', max_length=50),
        ),
    ]
