# Generated by Django 4.2.4 on 2023-11-15 11:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_company_name_company_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_az',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_az',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
