# Generated by Django 4.2.4 on 2023-11-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_category_name_az_category_name_en_category_parent_az_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent_az',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent_en',
        ),
    ]
