# Generated by Django 4.2.4 on 2024-01-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_product_aditional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='aditional_info_az',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='aditional_info_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
