# Generated by Django 4.2.4 on 2023-10-18 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.basemodel')),
                ('name', models.CharField(choices=[('Billing address', 'Billing address'), ('Shipping address', 'Shipping address'), ('Work address', 'Work address'), ('House address', 'House address')], max_length=100)),
                ('description', models.TextField(max_length=250)),
            ],
            bases=('accounts.basemodel',),
        ),
    ]
