# Generated by Django 4.2.4 on 2023-10-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_orderitems_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, to='settings.orderitems'),
        ),
    ]
