# Generated by Django 4.2.4 on 2023-10-18 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='name',
        ),
    ]
