# Generated by Django 4.2.4 on 2023-10-18 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_remove_newsletter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='name',
        ),
    ]
