# Generated by Django 4.2.4 on 2023-10-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Setting', 'verbose_name_plural': 'Setting'},
        ),
        migrations.RemoveField(
            model_name='settings',
            name='name',
        ),
    ]
