# Generated by Django 4.2.4 on 2023-11-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_country_payment_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_choices',
            field=models.CharField(choices=[('Pay by card', 'Pay by card'), ('Pay at the door', 'Pay at the door'), ('PayPal', 'PayPal')], max_length=200),
        ),
    ]
