# Generated by Django 4.2.4 on 2023-11-21 15:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_alter_payment_pay_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_az',
            field=ckeditor.fields.RichTextField(max_length=10000, null=True, verbose_name='Cavab'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=ckeditor.fields.RichTextField(max_length=10000, null=True, verbose_name='Cavab'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_az',
            field=ckeditor.fields.RichTextField(max_length=300, null=True, verbose_name='Sual'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=ckeditor.fields.RichTextField(max_length=300, null=True, verbose_name='Sual'),
        ),
    ]
